# Generated by Django 2.1.3 on 2019-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='label',
            field=models.CharField(choices=[('Bi', 'Business'), ('Wk', 'Work'), ('St', 'Study'), ('Ot', 'Other')], default='Ot', max_length=20),
        ),
    ]
